# Generated by Django 4.2 on 2025-05-06 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(default='Spark X1', max_length=50)),
                ('numero_serie', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)])),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Em manutenção'), ('DESATIVADO', 'Desativado')], default='DISPONIVEL', max_length=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobrenome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateTimeField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ANDAMENTO', 'Em andamento'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='ANDAMENTO', max_length=15)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
